/* Generated by Yosys 0.38+141 (git sha1 078b876f5, clang++ 14.0.0-1ubuntu1.1 -fPIC -Os) */

(* hdlname = "addplus" *)
(* top =  1  *)
(* src = "addveri/addplus.v:1.1-7.10" *)
module addplus(A, B, S);
  (* src = "addveri/addplus.v:2.11-2.12" *)
  input A;
  wire A;
  (* src = "addveri/addplus.v:3.11-3.12" *)
  input B;
  wire B;
  (* src = "addveri/addplus.v:4.12-4.13" *)
  output S;
  wire S;
  assign S = B ^(* src = "addveri/addplus.v:6.16-6.21|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  A;
endmodule
