/* Generated by Yosys 0.40+50 (git sha1 0f9ee20ea, g++ 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module lut(in, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire [1:0] _06_;
  wire [1:0] _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  input [1:0] in;
  wire [1:0] in;
  output out;
  wire out;
  assign _01_ = ~in[1];
  assign _00_ = ~in[0];
  assign _03_ = in[0] | _01_;
  assign _04_ = _00_ | in[1];
  assign _06_[1] = _09_ | _10_;
  assign _12_ = _07_[0] | _06_[1];
  assign _07_[0] = _08_ | _11_;
  assign _05_ = _00_ | _01_;
  assign _02_ = in[0] | in[1];
  assign _09_ = ~_03_;
  assign _10_ = ~_04_;
  assign _11_ = ~_02_;
  assign _08_ = ~_05_;
  assign out = _12_ ? _06_[1] : 1'hx;
  assign _06_[0] = 1'h0;
  assign _07_[1] = _06_[1];
endmodule
