/* Generated by Yosys 0.40+50 (git sha1 0f9ee20ea, g++ 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module blink(CLK, OUT);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire [12:0] _017_;
  wire [6:0] _018_;
  wire [2:0] _019_;
  wire [1:0] _020_;
  wire _021_;
  wire _022_;
  wire [26:0] _023_;
  wire [26:0] _024_;
  wire [26:0] _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  input CLK;
  wire CLK;
  output [3:0] OUT;
  wire [3:0] OUT;
  reg [26:0] cnt = 27'h0000000;
  reg onoff = 1'h0;
  always @(posedge CLK)
    if (!_021_) cnt[6] <= 1'h0;
    else cnt[6] <= _025_[6];
  always @(posedge CLK)
    if (!_021_) cnt[7] <= 1'h0;
    else cnt[7] <= _025_[7];
  always @(posedge CLK)
    if (!_021_) cnt[8] <= 1'h0;
    else cnt[8] <= _025_[8];
  always @(posedge CLK)
    if (!_021_) cnt[9] <= 1'h0;
    else cnt[9] <= _025_[9];
  always @(posedge CLK)
    if (!_021_) cnt[10] <= 1'h0;
    else cnt[10] <= _025_[10];
  always @(posedge CLK)
    if (!_021_) cnt[11] <= 1'h0;
    else cnt[11] <= _025_[11];
  always @(posedge CLK)
    if (!_021_) cnt[12] <= 1'h0;
    else cnt[12] <= _025_[12];
  always @(posedge CLK)
    if (!_021_) cnt[13] <= 1'h0;
    else cnt[13] <= _025_[13];
  always @(posedge CLK)
    if (!_021_) cnt[14] <= 1'h0;
    else cnt[14] <= _025_[14];
  always @(posedge CLK)
    if (!_021_) cnt[15] <= 1'h0;
    else cnt[15] <= _025_[15];
  always @(posedge CLK)
    if (!_021_) cnt[16] <= 1'h0;
    else cnt[16] <= _025_[16];
  always @(posedge CLK)
    if (!_021_) cnt[17] <= 1'h0;
    else cnt[17] <= _025_[17];
  always @(posedge CLK)
    if (!_021_) cnt[18] <= 1'h0;
    else cnt[18] <= _025_[18];
  always @(posedge CLK)
    if (!_021_) cnt[19] <= 1'h0;
    else cnt[19] <= _025_[19];
  always @(posedge CLK)
    if (!_021_) cnt[20] <= 1'h0;
    else cnt[20] <= _025_[20];
  always @(posedge CLK)
    if (!_021_) cnt[21] <= 1'h0;
    else cnt[21] <= _025_[21];
  always @(posedge CLK)
    if (!_021_) cnt[22] <= 1'h0;
    else cnt[22] <= _025_[22];
  always @(posedge CLK)
    if (!_021_) cnt[23] <= 1'h0;
    else cnt[23] <= _025_[23];
  always @(posedge CLK)
    if (!_021_) cnt[24] <= 1'h0;
    else cnt[24] <= _025_[24];
  always @(posedge CLK)
    if (!_021_) cnt[25] <= 1'h0;
    else cnt[25] <= _025_[25];
  always @(posedge CLK)
    if (!_021_) cnt[26] <= 1'h0;
    else cnt[26] <= _025_[26];
  always @(posedge CLK)
    if (!_021_) onoff <= _022_;
  always @(posedge CLK)
    if (!_021_) cnt[0] <= 1'h0;
    else cnt[0] <= _024_[0];
  always @(posedge CLK)
    if (!_021_) cnt[1] <= 1'h0;
    else cnt[1] <= _025_[1];
  always @(posedge CLK)
    if (!_021_) cnt[2] <= 1'h0;
    else cnt[2] <= _025_[2];
  always @(posedge CLK)
    if (!_021_) cnt[3] <= 1'h0;
    else cnt[3] <= _025_[3];
  always @(posedge CLK)
    if (!_021_) cnt[4] <= 1'h0;
    else cnt[4] <= _025_[4];
  always @(posedge CLK)
    if (!_021_) cnt[5] <= 1'h0;
    else cnt[5] <= _025_[5];
  assign _011_ = ~cnt[20];
  assign _012_ = ~cnt[21];
  assign _013_ = ~cnt[22];
  assign _014_ = ~cnt[24];
  assign _015_ = ~cnt[25];
  assign _016_ = ~cnt[26];
  assign _024_[0] = ~cnt[0];
  assign _017_[0] = _024_[0] | _000_;
  assign _017_[1] = _001_ | _002_;
  assign _017_[2] = _003_ | _004_;
  assign _017_[3] = cnt[6] | cnt[7];
  assign _017_[4] = _005_ | cnt[9];
  assign _017_[5] = cnt[10] | _006_;
  assign _017_[6] = _007_ | cnt[13];
  assign _017_[7] = _008_ | cnt[15];
  assign _017_[8] = _009_ | _010_;
  assign _017_[9] = cnt[18] | cnt[19];
  assign _017_[10] = _011_ | _012_;
  assign _017_[11] = _013_ | cnt[23];
  assign _017_[12] = _014_ | _015_;
  assign _018_[0] = _017_[0] | _017_[1];
  assign _018_[1] = _017_[2] | _017_[3];
  assign _018_[2] = _017_[4] | _017_[5];
  assign _018_[3] = _017_[6] | _017_[7];
  assign _018_[4] = _017_[8] | _017_[9];
  assign _018_[5] = _017_[10] | _017_[11];
  assign _018_[6] = _017_[12] | _016_;
  assign _019_[0] = _018_[0] | _018_[1];
  assign _019_[1] = _018_[2] | _018_[3];
  assign _019_[2] = _018_[4] | _018_[5];
  assign _020_[0] = _019_[0] | _019_[1];
  assign _020_[1] = _019_[2] | _018_[6];
  assign _021_ = _020_[0] | _020_[1];
  assign _022_ = ~onoff;
  assign _000_ = ~cnt[1];
  assign _001_ = ~cnt[2];
  assign _002_ = ~cnt[3];
  assign _003_ = ~cnt[4];
  assign _004_ = ~cnt[5];
  assign _005_ = ~cnt[8];
  assign _006_ = ~cnt[11];
  assign _007_ = ~cnt[12];
  assign _008_ = ~cnt[14];
  assign _009_ = ~cnt[16];
  assign _010_ = ~cnt[17];
  assign _025_[1] = cnt[1] ^ cnt[0];
  assign _025_[2] = cnt[2] ^ _023_[1];
  assign _025_[3] = cnt[3] ^ _023_[2];
  assign _025_[4] = cnt[4] ^ _023_[3];
  assign _025_[5] = cnt[5] ^ _023_[4];
  assign _025_[6] = cnt[6] ^ _023_[5];
  assign _025_[7] = cnt[7] ^ _023_[6];
  assign _025_[8] = cnt[8] ^ _023_[7];
  assign _025_[9] = cnt[9] ^ _023_[8];
  assign _025_[10] = cnt[10] ^ _023_[9];
  assign _025_[11] = cnt[11] ^ _023_[10];
  assign _025_[12] = cnt[12] ^ _023_[11];
  assign _025_[13] = cnt[13] ^ _023_[12];
  assign _025_[14] = cnt[14] ^ _023_[13];
  assign _025_[15] = cnt[15] ^ _023_[14];
  assign _025_[16] = cnt[16] ^ _023_[15];
  assign _025_[17] = cnt[17] ^ _023_[16];
  assign _025_[18] = cnt[18] ^ _023_[17];
  assign _025_[19] = cnt[19] ^ _023_[18];
  assign _025_[20] = cnt[20] ^ _023_[19];
  assign _025_[21] = cnt[21] ^ _023_[20];
  assign _025_[22] = cnt[22] ^ _023_[21];
  assign _025_[23] = cnt[23] ^ _023_[22];
  assign _025_[24] = cnt[24] ^ _023_[23];
  assign _025_[25] = cnt[25] ^ _023_[24];
  assign _025_[26] = cnt[26] ^ _023_[25];
  assign _023_[1] = cnt[1] & cnt[0];
  assign _023_[3] = _026_ & _023_[1];
  assign _023_[7] = _038_ & _023_[3];
  assign _023_[15] = _043_ & _023_[7];
  assign _026_ = cnt[3] & cnt[2];
  assign _027_ = cnt[5] & cnt[4];
  assign _028_ = cnt[7] & cnt[6];
  assign _029_ = cnt[9] & cnt[8];
  assign _030_ = cnt[11] & cnt[10];
  assign _031_ = cnt[13] & cnt[12];
  assign _032_ = cnt[15] & cnt[14];
  assign _033_ = cnt[17] & cnt[16];
  assign _034_ = cnt[19] & cnt[18];
  assign _035_ = cnt[21] & cnt[20];
  assign _036_ = cnt[23] & cnt[22];
  assign _037_ = cnt[25] & cnt[24];
  assign _038_ = _028_ & _027_;
  assign _039_ = _030_ & _029_;
  assign _040_ = _032_ & _031_;
  assign _041_ = _034_ & _033_;
  assign _042_ = _036_ & _035_;
  assign _043_ = _040_ & _039_;
  assign _044_ = _042_ & _041_;
  assign _023_[23] = _044_ & _023_[15];
  assign _023_[11] = _039_ & _023_[7];
  assign _023_[19] = _041_ & _023_[15];
  assign _023_[5] = _027_ & _023_[3];
  assign _023_[9] = _029_ & _023_[7];
  assign _023_[13] = _031_ & _023_[11];
  assign _023_[17] = _033_ & _023_[15];
  assign _023_[21] = _035_ & _023_[19];
  assign _023_[25] = _037_ & _023_[23];
  assign _023_[2] = cnt[2] & _023_[1];
  assign _023_[4] = cnt[4] & _023_[3];
  assign _023_[6] = cnt[6] & _023_[5];
  assign _023_[8] = cnt[8] & _023_[7];
  assign _023_[10] = cnt[10] & _023_[9];
  assign _023_[12] = cnt[12] & _023_[11];
  assign _023_[14] = cnt[14] & _023_[13];
  assign _023_[16] = cnt[16] & _023_[15];
  assign _023_[18] = cnt[18] & _023_[17];
  assign _023_[20] = cnt[20] & _023_[19];
  assign _023_[22] = cnt[22] & _023_[21];
  assign _023_[24] = cnt[24] & _023_[23];
  assign _023_[0] = cnt[0];
  assign _024_[26:1] = cnt[26:1];
  assign _025_[0] = _024_[0];
  assign OUT = { onoff, onoff, onoff, onoff };
endmodule
