package yosysjson

const (
	BUF    string = "$_BUF_"
	NOT    string = "$_NOT_"
	AND    string = "$_AND_"
	NAND   string = "$_NAND_"
	ANDNOT string = "$_ANDNOT_"
	OR     string = "$_OR_"
	NOR    string = "$_NOR_"
	ORNOT  string = "$_ORNOT_"
	XOR    string = "$_XOR_"
	XNOR   string = "$_XNOR_"
	//AOI3   string = "$_AOI3_"
	//OAI3   string = "$_OAI3_"
	//AOI4   string = "$_AOI4_"
	//OAI4   string = "$_OAI4_"
	MUX  string = "$_MUX_"
	NMUX string = "$_NMUX_"
	//MUX4  string = "$_MUX4_"
	//MUX8  string = "$_MUX8_"
	//MUX16 string = "$_MUX16_"
	//TBUF  string = "$_TBUF_"
	DFF_N    string = "$_DFF_N_"
	DFF_P    string = "$_DFF_P_"
	DLATCH_N string = "$_DLATCH_N_"
	DLATCH_P string = "$_DLATCH_P_"
)
