/* Generated by Yosys 0.40+50 (git sha1 0f9ee20ea, g++ 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module fulladd(A, B, CIN, Q, COUT);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  input A;
  wire A;
  input B;
  wire B;
  input CIN;
  wire CIN;
  output COUT;
  wire COUT;
  output Q;
  wire Q;
  assign _04_ = A ^ B;
  assign Q = _04_ ^ CIN;
  assign _00_ = A & B;
  assign _01_ = B & CIN;
  assign _03_ = _00_ | _01_;
  assign _02_ = CIN & A;
  assign COUT = _03_ | _02_;
endmodule
