/* Generated by Yosys 0.38+141 (git sha1 078b876f5, clang++ 14.0.0-1ubuntu1.1 -fPIC -Os) */

(* CORE_GENERATION_INFO = "muladd_muladd,hls_ip_2023_2_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.874000,HLS_SYN_LAT=1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=230,HLS_SYN_LUT=313,HLS_VERSION=2023_2_2}" *)
(* hdlname = "muladd" *)
(* dynports =  1  *)
(* top =  1  *)
(* src = "workspace/addveri/muladd.v:11.1-217.10" *)
module muladd(ap_clk, ap_rst_n, s_axi_control_AWVALID, s_axi_control_AWREADY, s_axi_control_AWADDR, s_axi_control_WVALID, s_axi_control_WREADY, s_axi_control_WDATA, s_axi_control_WSTRB, s_axi_control_ARVALID, s_axi_control_ARREADY, s_axi_control_ARADDR, s_axi_control_RVALID, s_axi_control_RREADY, s_axi_control_RDATA, s_axi_control_RRESP, s_axi_control_BVALID, s_axi_control_BREADY, s_axi_control_BRESP, interrupt);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  (* src = "workspace/addveri/muladd.v:144.10-144.26" *)
  wire _004_;
  (* force_downto = 32'd1 *)
  (* src = "workspace/addveri/muladd.v:0.0-0.0|workspace/addveri/muladd.v:186.5-200.12|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:571.28-571.29" *)
  wire [3:0] _005_;
  (* force_downto = 32'd1 *)
  (* src = "workspace/addveri/muladd.v:0.0-0.0|workspace/addveri/muladd.v:186.5-200.12|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:583.28-583.35" *)
  wire [3:0] _006_;
  (* force_downto = 32'd1 *)
  (* src = "workspace/addveri/muladd.v:0.0-0.0|workspace/addveri/muladd.v:186.5-200.12|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:573.22-573.23" *)
  wire [1:0] _007_;
  (* force_downto = 32'd1 *)
  (* src = "workspace/addveri/muladd.v:0.0-0.0|workspace/addveri/muladd.v:186.5-200.12|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:578.19-578.22" *)
  wire [1:0] _008_;
  (* force_downto = 32'd1 *)
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "31" *)
  wire [31:0] _009_;
  (* force_downto = 32'd1 *)
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:270.23-270.24" *)
  wire [31:0] _010_;
  (* force_downto = 32'd1 *)
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:214.23-214.24" *)
  (* unused_bits = "31" *)
  wire [31:0] _011_;
  (* src = "workspace/addveri/muladd.v:0.0-0.0|workspace/addveri/muladd.v:186.5-200.12|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:597.13-597.15" *)
  wire _012_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _013_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _014_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _015_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _016_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _017_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _018_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _019_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _020_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _021_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _022_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _023_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _024_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _025_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _026_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _027_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _028_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _029_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _030_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _031_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _032_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _033_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _034_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _035_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _036_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _037_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _038_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _039_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _040_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _041_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _042_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _043_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _044_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _045_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _046_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _047_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _048_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _049_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _050_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _051_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _052_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _053_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _054_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _055_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _056_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _057_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _058_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _059_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _060_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _061_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _062_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _063_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _064_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _065_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _066_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _067_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _068_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _069_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _070_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _071_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _072_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _073_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _074_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _075_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _076_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _077_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _078_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _079_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _080_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _081_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _082_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _083_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _084_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _085_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _086_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _087_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _088_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _089_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _090_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _091_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _092_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _093_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _094_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _095_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _096_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _097_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _098_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _099_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _100_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _101_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _102_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _103_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _104_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _105_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _106_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _107_;
  (* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _108_;
  (* src = "workspace/addveri/muladd.v:71.14-71.24" *)
  wire [3:0] a_address0;
  (* src = "workspace/addveri/muladd.v:72.8-72.13" *)
  wire a_ce0;
  (* src = "workspace/addveri/muladd.v:73.15-73.19" *)
  wire [31:0] a_q0;
  (* fsm_encoding = "none" *)
  (* src = "workspace/addveri/muladd.v:68.41-68.50" *)
  reg [1:0] ap_CS_fsm = 2'h1;
  (* src = "workspace/addveri/muladd.v:69.9-69.25" *)
  wire ap_CS_fsm_state1;
  (* src = "workspace/addveri/muladd.v:78.9-78.25" *)
  wire ap_CS_fsm_state2;
  (* src = "workspace/addveri/muladd.v:79.13-79.22" *)
  wire [1:0] ap_NS_fsm;
  (* src = "workspace/addveri/muladd.v:81.9-81.29" *)
  wire ap_ST_fsm_state2_blk;
  (* src = "workspace/addveri/muladd.v:43.9-43.15" *)
  input ap_clk;
  wire ap_clk;
  (* src = "workspace/addveri/muladd.v:66.8-66.15" *)
  wire ap_done;
  (* src = "workspace/addveri/muladd.v:67.8-67.15" *)
  wire ap_idle;
  (* src = "workspace/addveri/muladd.v:70.8-70.16" *)
  wire ap_ready;
  (* src = "workspace/addveri/muladd.v:77.15-77.24" *)
  wire [31:0] ap_return;
  (* src = "workspace/addveri/muladd.v:44.9-44.17" *)
  input ap_rst_n;
  wire ap_rst_n;
  (* src = "workspace/addveri/muladd.v:64.9-64.21" *)
  wire ap_rst_n_inv;
  (* src = "workspace/addveri/muladd.v:65.9-65.17" *)
  wire ap_start;
  (* src = "workspace/addveri/muladd.v:74.14-74.24" *)
  wire [3:0] b_address0;
  (* src = "workspace/addveri/muladd.v:75.8-75.13" *)
  wire b_ce0;
  (* src = "workspace/addveri/muladd.v:76.15-76.19" *)
  wire [31:0] b_q0;
  (* src = "workspace/addveri/muladd.v:62.10-62.19" *)
  output interrupt;
  wire interrupt;
  (* src = "workspace/addveri/muladd.v:54.43-54.63" *)
  input [7:0] s_axi_control_ARADDR;
  wire [7:0] s_axi_control_ARADDR;
  (* src = "workspace/addveri/muladd.v:53.10-53.31" *)
  output s_axi_control_ARREADY;
  wire s_axi_control_ARREADY;
  (* src = "workspace/addveri/muladd.v:52.9-52.30" *)
  input s_axi_control_ARVALID;
  wire s_axi_control_ARVALID;
  (* src = "workspace/addveri/muladd.v:47.43-47.63" *)
  input [7:0] s_axi_control_AWADDR;
  wire [7:0] s_axi_control_AWADDR;
  (* src = "workspace/addveri/muladd.v:46.10-46.31" *)
  output s_axi_control_AWREADY;
  wire s_axi_control_AWREADY;
  (* src = "workspace/addveri/muladd.v:45.9-45.30" *)
  input s_axi_control_AWVALID;
  wire s_axi_control_AWVALID;
  (* src = "workspace/addveri/muladd.v:60.9-60.29" *)
  input s_axi_control_BREADY;
  wire s_axi_control_BREADY;
  (* src = "workspace/addveri/muladd.v:61.15-61.34" *)
  output [1:0] s_axi_control_BRESP;
  wire [1:0] s_axi_control_BRESP;
  (* src = "workspace/addveri/muladd.v:59.10-59.30" *)
  output s_axi_control_BVALID;
  wire s_axi_control_BVALID;
  (* src = "workspace/addveri/muladd.v:57.44-57.63" *)
  output [31:0] s_axi_control_RDATA;
  wire [31:0] s_axi_control_RDATA;
  (* src = "workspace/addveri/muladd.v:56.9-56.29" *)
  input s_axi_control_RREADY;
  wire s_axi_control_RREADY;
  (* src = "workspace/addveri/muladd.v:58.15-58.34" *)
  output [1:0] s_axi_control_RRESP;
  wire [1:0] s_axi_control_RRESP;
  (* src = "workspace/addveri/muladd.v:55.10-55.30" *)
  output s_axi_control_RVALID;
  wire s_axi_control_RVALID;
  (* src = "workspace/addveri/muladd.v:50.43-50.62" *)
  input [31:0] s_axi_control_WDATA;
  wire [31:0] s_axi_control_WDATA;
  (* src = "workspace/addveri/muladd.v:49.10-49.30" *)
  output s_axi_control_WREADY;
  wire s_axi_control_WREADY;
  (* src = "workspace/addveri/muladd.v:51.44-51.63" *)
  input [3:0] s_axi_control_WSTRB;
  wire [3:0] s_axi_control_WSTRB;
  (* src = "workspace/addveri/muladd.v:48.9-48.29" *)
  input s_axi_control_WVALID;
  wire s_axi_control_WVALID;
  (* src = "workspace/addveri/muladd.v:127.1-133.4" *)
  always @(posedge ap_clk)
    if (!ap_rst_n) ap_CS_fsm[0] <= 1'h1;
    else ap_CS_fsm[0] <= ap_NS_fsm[0];
  (* src = "workspace/addveri/muladd.v:127.1-133.4" *)
  always @(posedge ap_clk)
    if (!ap_rst_n) ap_CS_fsm[1] <= 1'h0;
    else ap_CS_fsm[1] <= ap_NS_fsm[1];
  assign _000_ = ~ap_CS_fsm[1];
  assign _001_ = ~ap_CS_fsm[0];
  assign _002_ = ap_CS_fsm[0] |(* src = "workspace/addveri/muladd.v:0.0-0.0|workspace/addveri/muladd.v:186.5-200.12" *)  _000_;
  assign _003_ = _001_ |(* src = "workspace/addveri/muladd.v:0.0-0.0|workspace/addveri/muladd.v:186.5-200.12" *)  ap_CS_fsm[1];
  assign _008_[0] = _006_[0] |(* src = "workspace/addveri/muladd.v:0.0-0.0|workspace/addveri/muladd.v:186.5-200.12|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:593.20-593.31" *)  _006_[2];
  assign _012_ = _006_[0] |(* src = "workspace/addveri/muladd.v:0.0-0.0|workspace/addveri/muladd.v:186.5-200.12|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:597.13-597.15" *)  _007_[1];
  assign _006_[0] = ~(* src = "workspace/addveri/muladd.v:0.0-0.0|workspace/addveri/muladd.v:186.5-200.12" *) _002_;
  assign _007_[1] = ~(* src = "workspace/addveri/muladd.v:0.0-0.0|workspace/addveri/muladd.v:186.5-200.12" *) _003_;
  assign _005_[2] = ~(* src = "workspace/addveri/muladd.v:188.17-188.66|workspace/addveri/muladd.v:188.13-192.16" *) a_ce0;
  assign ap_NS_fsm[0] = _012_ ? (* src = "workspace/addveri/muladd.v:0.0-0.0|workspace/addveri/muladd.v:186.5-200.12|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:597.13-597.25" *) _008_[0] : 1'hx;
  assign ap_NS_fsm[1] = _012_ ? (* src = "workspace/addveri/muladd.v:0.0-0.0|workspace/addveri/muladd.v:186.5-200.12|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:597.13-597.25" *) _006_[3] : 1'hx;
  assign _004_ = ~(* src = "workspace/addveri/muladd.v:144.10-144.26" *) ap_start;
  assign ap_rst_n_inv = ~(* src = "workspace/addveri/muladd.v:212.20-212.29" *) ap_rst_n;
  assign a_ce0 = ap_start &(* src = "workspace/addveri/muladd.v:136.10-136.57" *)  ap_CS_fsm[0];
  assign ap_idle = _004_ &(* src = "workspace/addveri/muladd.v:162.10-162.57" *)  ap_CS_fsm[0];
  assign _006_[2] = _005_[2] &(* src = "workspace/addveri/muladd.v:0.0-0.0|workspace/addveri/muladd.v:186.5-200.12|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  _007_[1];
  assign _006_[3] = a_ce0 &(* src = "workspace/addveri/muladd.v:0.0-0.0|workspace/addveri/muladd.v:186.5-200.12|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  _007_[1];
  assign ap_return[1] = _010_[1] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _009_[0];
  assign ap_return[2] = _010_[2] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _009_[1];
  assign ap_return[3] = _010_[3] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _009_[2];
  assign ap_return[4] = _010_[4] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _009_[3];
  assign ap_return[5] = _010_[5] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _009_[4];
  assign ap_return[6] = _010_[6] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _009_[5];
  assign ap_return[7] = _010_[7] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _009_[6];
  assign ap_return[8] = _010_[8] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _009_[7];
  assign ap_return[9] = _010_[9] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _009_[8];
  assign ap_return[10] = _010_[10] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _009_[9];
  assign ap_return[11] = _010_[11] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _009_[10];
  assign ap_return[12] = _010_[12] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _009_[11];
  assign ap_return[13] = _010_[13] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _009_[12];
  assign ap_return[14] = _010_[14] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _009_[13];
  assign ap_return[15] = _010_[15] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _009_[14];
  assign ap_return[16] = _010_[16] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _009_[15];
  assign ap_return[17] = _010_[17] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _009_[16];
  assign ap_return[18] = _010_[18] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _009_[17];
  assign ap_return[19] = _010_[19] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _009_[18];
  assign ap_return[20] = _010_[20] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _009_[19];
  assign ap_return[21] = _010_[21] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _009_[20];
  assign ap_return[22] = _010_[22] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _009_[21];
  assign ap_return[23] = _010_[23] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _009_[22];
  assign ap_return[24] = _010_[24] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _009_[23];
  assign ap_return[25] = _010_[25] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _009_[24];
  assign ap_return[26] = _010_[26] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _009_[25];
  assign ap_return[27] = _010_[27] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _009_[26];
  assign ap_return[28] = _010_[28] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _009_[27];
  assign ap_return[29] = _010_[29] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _009_[28];
  assign ap_return[30] = _010_[30] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _009_[29];
  assign ap_return[31] = _010_[31] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _009_[30];
  assign ap_return[0] = a_q0[0] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  b_q0[0];
  assign _010_[1] = a_q0[1] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  b_q0[1];
  assign _010_[2] = a_q0[2] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  b_q0[2];
  assign _010_[3] = a_q0[3] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  b_q0[3];
  assign _010_[4] = a_q0[4] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  b_q0[4];
  assign _010_[5] = a_q0[5] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  b_q0[5];
  assign _010_[6] = a_q0[6] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  b_q0[6];
  assign _010_[7] = a_q0[7] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  b_q0[7];
  assign _010_[8] = a_q0[8] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  b_q0[8];
  assign _010_[9] = a_q0[9] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  b_q0[9];
  assign _010_[10] = a_q0[10] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  b_q0[10];
  assign _010_[11] = a_q0[11] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  b_q0[11];
  assign _010_[12] = a_q0[12] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  b_q0[12];
  assign _010_[13] = a_q0[13] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  b_q0[13];
  assign _010_[14] = a_q0[14] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  b_q0[14];
  assign _010_[15] = a_q0[15] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  b_q0[15];
  assign _010_[16] = a_q0[16] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  b_q0[16];
  assign _010_[17] = a_q0[17] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  b_q0[17];
  assign _010_[18] = a_q0[18] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  b_q0[18];
  assign _010_[19] = a_q0[19] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  b_q0[19];
  assign _010_[20] = a_q0[20] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  b_q0[20];
  assign _010_[21] = a_q0[21] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  b_q0[21];
  assign _010_[22] = a_q0[22] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  b_q0[22];
  assign _010_[23] = a_q0[23] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  b_q0[23];
  assign _010_[24] = a_q0[24] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  b_q0[24];
  assign _010_[25] = a_q0[25] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  b_q0[25];
  assign _010_[26] = a_q0[26] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  b_q0[26];
  assign _010_[27] = a_q0[27] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  b_q0[27];
  assign _010_[28] = a_q0[28] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  b_q0[28];
  assign _010_[29] = a_q0[29] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  b_q0[29];
  assign _010_[30] = a_q0[30] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  b_q0[30];
  assign _010_[31] = a_q0[31] ^(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  b_q0[31];
  assign _009_[0] = a_q0[0] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  b_q0[0];
  assign _011_[1] = a_q0[1] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  b_q0[1];
  assign _011_[2] = a_q0[2] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  b_q0[2];
  assign _011_[3] = a_q0[3] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  b_q0[3];
  assign _011_[4] = a_q0[4] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  b_q0[4];
  assign _011_[5] = a_q0[5] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  b_q0[5];
  assign _011_[6] = a_q0[6] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  b_q0[6];
  assign _011_[7] = a_q0[7] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  b_q0[7];
  assign _011_[8] = a_q0[8] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  b_q0[8];
  assign _011_[9] = a_q0[9] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  b_q0[9];
  assign _011_[10] = a_q0[10] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  b_q0[10];
  assign _011_[11] = a_q0[11] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  b_q0[11];
  assign _011_[12] = a_q0[12] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  b_q0[12];
  assign _011_[13] = a_q0[13] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  b_q0[13];
  assign _011_[14] = a_q0[14] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  b_q0[14];
  assign _011_[15] = a_q0[15] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  b_q0[15];
  assign _011_[16] = a_q0[16] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  b_q0[16];
  assign _011_[17] = a_q0[17] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  b_q0[17];
  assign _011_[18] = a_q0[18] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  b_q0[18];
  assign _011_[19] = a_q0[19] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  b_q0[19];
  assign _011_[20] = a_q0[20] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  b_q0[20];
  assign _011_[21] = a_q0[21] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  b_q0[21];
  assign _011_[22] = a_q0[22] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  b_q0[22];
  assign _011_[23] = a_q0[23] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  b_q0[23];
  assign _011_[24] = a_q0[24] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  b_q0[24];
  assign _011_[25] = a_q0[25] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  b_q0[25];
  assign _011_[26] = a_q0[26] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  b_q0[26];
  assign _011_[27] = a_q0[27] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  b_q0[27];
  assign _011_[28] = a_q0[28] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  b_q0[28];
  assign _011_[29] = a_q0[29] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  b_q0[29];
  assign _011_[30] = a_q0[30] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  b_q0[30];
  assign _013_ = _010_[1] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)  _009_[0];
  assign _014_ = _010_[3] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)  _011_[2];
  assign _015_ = _010_[5] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)  _011_[4];
  assign _016_ = _010_[7] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)  _011_[6];
  assign _017_ = _010_[9] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)  _011_[8];
  assign _018_ = _010_[11] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)  _011_[10];
  assign _019_ = _010_[13] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)  _011_[12];
  assign _020_ = _010_[15] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)  _011_[14];
  assign _021_ = _010_[17] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)  _011_[16];
  assign _022_ = _010_[19] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)  _011_[18];
  assign _023_ = _010_[21] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)  _011_[20];
  assign _024_ = _010_[23] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)  _011_[22];
  assign _025_ = _010_[25] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)  _011_[24];
  assign _026_ = _010_[27] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)  _011_[26];
  assign _027_ = _010_[29] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)  _011_[28];
  assign _028_ = _039_ &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)  _009_[1];
  assign _029_ = _041_ &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)  _088_;
  assign _030_ = _043_ &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)  _090_;
  assign _031_ = _045_ &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)  _092_;
  assign _032_ = _047_ &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)  _094_;
  assign _033_ = _049_ &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)  _096_;
  assign _034_ = _051_ &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)  _098_;
  assign _035_ = _053_ &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)  _009_[3];
  assign _036_ = _055_ &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)  _102_;
  assign _037_ = _057_ &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)  _104_;
  assign _038_ = _059_ &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)  _009_[7];
  assign _039_ = _010_[3] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)  _010_[2];
  assign _040_ = _010_[5] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)  _010_[4];
  assign _041_ = _010_[7] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)  _010_[6];
  assign _042_ = _010_[9] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)  _010_[8];
  assign _043_ = _010_[11] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)  _010_[10];
  assign _044_ = _010_[13] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)  _010_[12];
  assign _045_ = _010_[15] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)  _010_[14];
  assign _046_ = _010_[17] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)  _010_[16];
  assign _047_ = _010_[19] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)  _010_[18];
  assign _048_ = _010_[21] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)  _010_[20];
  assign _049_ = _010_[23] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)  _010_[22];
  assign _050_ = _010_[25] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)  _010_[24];
  assign _051_ = _010_[27] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)  _010_[26];
  assign _052_ = _010_[29] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)  _010_[28];
  assign _053_ = _041_ &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)  _040_;
  assign _054_ = _043_ &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)  _042_;
  assign _055_ = _045_ &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)  _044_;
  assign _056_ = _047_ &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)  _046_;
  assign _057_ = _049_ &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)  _048_;
  assign _058_ = _051_ &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)  _050_;
  assign _059_ = _055_ &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)  _054_;
  assign _060_ = _057_ &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)  _056_;
  assign _061_ = _060_ &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)  _009_[15];
  assign _062_ = _054_ &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)  _009_[7];
  assign _063_ = _056_ &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)  _009_[15];
  assign _064_ = _058_ &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)  _009_[23];
  assign _065_ = _040_ &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)  _009_[3];
  assign _066_ = _042_ &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)  _009_[7];
  assign _067_ = _044_ &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)  _009_[11];
  assign _068_ = _046_ &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)  _009_[15];
  assign _069_ = _048_ &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)  _009_[19];
  assign _070_ = _050_ &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)  _009_[23];
  assign _071_ = _052_ &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)  _009_[27];
  assign _072_ = _010_[2] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)  _009_[1];
  assign _073_ = _010_[4] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)  _009_[3];
  assign _074_ = _010_[6] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)  _009_[5];
  assign _075_ = _010_[8] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)  _009_[7];
  assign _076_ = _010_[10] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)  _009_[9];
  assign _077_ = _010_[12] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)  _009_[11];
  assign _078_ = _010_[14] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)  _009_[13];
  assign _079_ = _010_[16] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)  _009_[15];
  assign _080_ = _010_[18] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)  _009_[17];
  assign _081_ = _010_[20] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)  _009_[19];
  assign _082_ = _010_[22] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)  _009_[21];
  assign _083_ = _010_[24] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)  _009_[23];
  assign _084_ = _010_[26] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)  _009_[25];
  assign _085_ = _010_[28] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)  _009_[27];
  assign _086_ = _010_[30] &(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)  _009_[29];
  assign _009_[1] = _011_[1] |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)  _013_;
  assign _087_ = _011_[3] |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)  _014_;
  assign _088_ = _011_[5] |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)  _015_;
  assign _089_ = _011_[7] |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)  _016_;
  assign _090_ = _011_[9] |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)  _017_;
  assign _091_ = _011_[11] |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)  _018_;
  assign _092_ = _011_[13] |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)  _019_;
  assign _093_ = _011_[15] |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)  _020_;
  assign _094_ = _011_[17] |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)  _021_;
  assign _095_ = _011_[19] |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)  _022_;
  assign _096_ = _011_[21] |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)  _023_;
  assign _097_ = _011_[23] |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)  _024_;
  assign _098_ = _011_[25] |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)  _025_;
  assign _099_ = _011_[27] |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)  _026_;
  assign _100_ = _011_[29] |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)  _027_;
  assign _009_[3] = _087_ |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)  _028_;
  assign _101_ = _089_ |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)  _029_;
  assign _102_ = _091_ |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)  _030_;
  assign _103_ = _093_ |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)  _031_;
  assign _104_ = _095_ |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)  _032_;
  assign _105_ = _097_ |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)  _033_;
  assign _106_ = _099_ |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)  _034_;
  assign _009_[7] = _101_ |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)  _035_;
  assign _107_ = _103_ |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)  _036_;
  assign _108_ = _105_ |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)  _037_;
  assign _009_[15] = _107_ |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)  _038_;
  assign _009_[23] = _108_ |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.12-248.41" *)  _061_;
  assign _009_[11] = _102_ |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.12-248.41" *)  _062_;
  assign _009_[19] = _104_ |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.12-248.41" *)  _063_;
  assign _009_[27] = _106_ |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.12-248.41" *)  _064_;
  assign _009_[5] = _088_ |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.12-248.41" *)  _065_;
  assign _009_[9] = _090_ |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.12-248.41" *)  _066_;
  assign _009_[13] = _092_ |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.12-248.41" *)  _067_;
  assign _009_[17] = _094_ |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.12-248.41" *)  _068_;
  assign _009_[21] = _096_ |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.12-248.41" *)  _069_;
  assign _009_[25] = _098_ |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.12-248.41" *)  _070_;
  assign _009_[29] = _100_ |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.12-248.41" *)  _071_;
  assign _009_[2] = _011_[2] |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.12-248.41" *)  _072_;
  assign _009_[4] = _011_[4] |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.12-248.41" *)  _073_;
  assign _009_[6] = _011_[6] |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.12-248.41" *)  _074_;
  assign _009_[8] = _011_[8] |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.12-248.41" *)  _075_;
  assign _009_[10] = _011_[10] |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.12-248.41" *)  _076_;
  assign _009_[12] = _011_[12] |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.12-248.41" *)  _077_;
  assign _009_[14] = _011_[14] |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.12-248.41" *)  _078_;
  assign _009_[16] = _011_[16] |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.12-248.41" *)  _079_;
  assign _009_[18] = _011_[18] |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.12-248.41" *)  _080_;
  assign _009_[20] = _011_[20] |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.12-248.41" *)  _081_;
  assign _009_[22] = _011_[22] |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.12-248.41" *)  _082_;
  assign _009_[24] = _011_[24] |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.12-248.41" *)  _083_;
  assign _009_[26] = _011_[26] |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.12-248.41" *)  _084_;
  assign _009_[28] = _011_[28] |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.12-248.41" *)  _085_;
  assign _009_[30] = _011_[30] |(* src = "workspace/addveri/muladd.v:209.21-209.32|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/ai-i2lab/oss-cad-suite/lib/../share/yosys/techmap.v:248.12-248.41" *)  _086_;
  (* module_not_derived = 32'd1 *)
  (* src = "workspace/addveri/muladd.v:92.1-125.2" *)
  muladd_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH(32'sd8),
    .C_S_AXI_DATA_WIDTH(32'sd32)
  ) control_s_axi_U (
    .ACLK(ap_clk),
    .ACLK_EN(1'h1),
    .ARADDR(s_axi_control_ARADDR),
    .ARESET(ap_rst_n_inv),
    .ARREADY(s_axi_control_ARREADY),
    .ARVALID(s_axi_control_ARVALID),
    .AWADDR(s_axi_control_AWADDR),
    .AWREADY(s_axi_control_AWREADY),
    .AWVALID(s_axi_control_AWVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .BVALID(s_axi_control_BVALID),
    .RDATA(s_axi_control_RDATA),
    .RREADY(s_axi_control_RREADY),
    .RRESP(s_axi_control_RRESP),
    .RVALID(s_axi_control_RVALID),
    .WDATA(s_axi_control_WDATA),
    .WREADY(s_axi_control_WREADY),
    .WSTRB(s_axi_control_WSTRB),
    .WVALID(s_axi_control_WVALID),
    .a_address0(4'hf),
    .a_ce0(a_ce0),
    .a_q0(a_q0),
    .ap_done(ap_CS_fsm[1]),
    .ap_idle(ap_idle),
    .ap_ready(ap_CS_fsm[1]),
    .ap_return(ap_return),
    .ap_start(ap_start),
    .b_address0(4'hf),
    .b_ce0(a_ce0),
    .b_q0(b_q0),
    .interrupt(interrupt)
  );
  assign { _005_[3], _005_[1:0] } = { a_ce0, 2'h1 };
  assign _006_[1] = 1'h0;
  assign _007_[0] = _006_[0];
  assign _008_[1] = _006_[3];
  assign _010_[0] = ap_return[0];
  assign _011_[0] = _009_[0];
  assign a_address0 = 4'hf;
  assign ap_CS_fsm_state1 = ap_CS_fsm[0];
  assign ap_CS_fsm_state2 = ap_CS_fsm[1];
  assign ap_ST_fsm_state2_blk = 1'h0;
  assign ap_done = ap_CS_fsm[1];
  assign ap_ready = ap_CS_fsm[1];
  assign b_address0 = 4'hf;
  assign b_ce0 = a_ce0;
endmodule
